// Backward compatibility re-export from new ICT module
// All ICT functionality is now in src/lib/ict/

export {
  // Types
  type QuarterPhase,
  type AMDPhase,
  type DayOfWeek,
  type ProfileType,
  type ExpectedAction,
  type DailyBias,
  type QuarterInfo,
  type AMDPhaseInfo,
  type DayProfile,
  type SessionQuarter,
  type IntradayProfile,
  type CurrentMarketState,
  type WeeklyTemplateId,
  type WeeklyTemplate,
  type TimeMacro,
  type MacroCategory,
  type MacroSession,
  type QuarterState,
  type SessionStrategy,
  // Constants
  AMD_PHASES,
  WEEKLY_PROFILES,
  WEEKLY_TEMPLATES,
  SESSION_QUARTERS,
  INTRADAY_PROFILES,
  KEY_TIMES,
  TIME_MACROS,
  SESSION_STRATEGIES,
  TEMPLATE_CATEGORIES,
  // Functions
  getCurrentDayOfWeek,
  getDayProfile,
  getCurrentSessionQuarter,
  getCurrentAMDPhase,
  getIntradayProfile,
  getNextKeyTime,
  getCurrentSessionName,
  getCurrentMarketState,
  formatTimeDisplay,
  isInKillzone,
  getSessionProgress,
  getCurrentMacro,
  getNextMacro,
  getMacroProgress,
  getQuarterState,
  getTemplatesByCategory,
  getTemplatesByBias,
} from './ict';
